CREATE TABLE livres (
	ID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	AUTHOR_ID INT NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT fk_id_author FOREIGN KEY (AUTHOR_ID) REFERENCES authors (ID)
);