INSERT INTO bookshop.authors (FIRST_NAME, LAST_NAME) VALUES ('SCOT', 'FITZGERALD');
INSERT INTO bookshop.authors (FIRST_NAME, LAST_NAME) VALUES ('Stefan', 'ZWEIG');
INSERT INTO bookshop.authors (FIRST_NAME, LAST_NAME) VALUES ('Michel', 'ONFRAY');
INSERT INTO bookshop.authors (FIRST_NAME, LAST_NAME) VALUES ('Boris', 'VIAN');

